/*
QUERY 1
WARNNING:   THIS QUERY SHOW THE DAILY REVENUES. A NON SELLING DAY CAN NOT BE SHOWN INSTEAD OF 'ventes' = 0
            A DAILY DATE REFERENCE (DIMENSION) CAN FIX THIS ISSUE
NOTE:       WE NOT USE THE SQL "BETWEEN" CLAUSE BECAUSE IT'S SQL ENGINE DEPENDENT => EXCLUSIVE/INCLUSIVE
*/
SELECT
        tx.date
    ,   SUM(tx.prod_price * tx.prod_qty) as ventes
FROM `TRANSACTION` as tx
WHERE 
        tx.date >= '2019-01-01'
    AND tx.date < '2020-01-01'
GROUP BY 1
ORDER BY 1 ASC
;